pipenv run flake8 --config=test/test.cfg
echo Type checking main codebase...
pipenv run mypy --config-file=test/test.cfg *.py kac_drumset
echo Type checking testing library...
pipenv run mypy --config-file=test/test.cfg test
pipenv run python test/test.py